### ISSUE TITLE
Not working with OpenJDK 11

### ISSUE THREAD

**Issue by ajayg2808** [xipki/pkcs11wrapper#13]
Unable to load **PKCS11Library.dll**

Getting below error when try to load library.
[java11_error.txt](https://github.com/xipki/pkcs11wrapper/files/9138024/java11_error.txt)

## > It worked fine with oracle jre 8.

Thank you!

**Comment by xipki** [comment]
Could you also provide the hs_err_pid*.log file, and what is the JDK's vendor (output of java -version)?

**Comment by xipki** [comment]
Close this issue due to long-time inactivity. BTW, this project is deprecated and will not be supported anymore, please use https://github.com/xipki/ipkcs11wrapper instead.
