### ISSUE TITLE
sunPKCS11 on Java 9+

### ISSUE THREAD

**Issue by herbert-h** [xipki/pkcs11wrapper#2]
Hello,

Currently I work on a cryptography project where we implement all communication with HSM using sunPKCS11, however in the most current versions of Java the sunPKCS11 package is no longer directly accessible, and being encapsulated in a provider, something that limits a lot of our work, especially the use of DES2 keys among other functions.

This project also directly accesses the sunPKCS11 classes (ex. import sun.security.pkcs11.wrapper.PKCS11). I would like to know if you already have any idea how this will be solved using Java version 11 for example.

All the best, thank you.

**Comment by xipki** [comment]
Die you tried it under JDK 11?

**Comment by xipki** [comment]
Just tested JDK 10 and 11 with openjdk of the vendor zulu. It works.

**Comment by xipki** [comment]
You may find example on the usage of this Pkcs11wrapper under https://github.com/xipki/pkcs11wrapper/tree/sunpkcs11/examples.
