### ISSUE TITLE
info about right pattern on hsm restart

### ISSUE THREAD

**Issue by armando-basile** [xipki/pkcs11wrapper#3]
Hi Xipki, i would like to implement a right pattern in case of restart hsm necessary.
I saw that, after i restarted hsm, i received this error on next use
`Unknwon mechanism with code: 0x0000000080000384`

Which should be a right pattern ?
- Is there a method to check module state ? So i could try to check state before perform operations.
- If there is a specific exception, i could try to manage exception and launch reinit module (should i finalize and initialize in this case ?)
- i could try to use getInfo() to detect if module state is no good ?
- Should i shutdown and restart application completely ?

**Comment by xipki** [comment]
1. As mentioned in #1, the re-init of HSM module cannot be implemented. You need to restart the JVM.
2. Related to the Unknown mechanism error, please provide more log information.

**Comment by armando-basile** [comment]
Ok, so, of i understand, of hsm power off and after power on i need to restart jvm to reinitialize modulo and go away, it's right ?

Thanks

**Comment by xipki** [comment]
Yes, you need to restart the jvm.
